### ISSUE TITLE
Add a list of language server libraries

### ISSUE THREAD

**Issue by Timmmm** [langserver/langserver.github.io#117]
It would be nice to have a list that answers the question "I want to write a language server in <my favourite language>. Is there a library I can use to take care of all the protocol stuff?"

* Go: https://github.com/sourcegraph/go-langserver
* Rust: https://github.com/gluon-lang/languageserver-types, https://github.com/smith61/rls_proto (unmaintained), https://github.com/RustDT/RustLSP (unmaintained).
* C#: https://github.com/matarillo/LanguageServerProtocol

etc.

**Comment by Timmmm** [comment]
Think you might have closed the wrong issue unless I missed something. (Sorry I never got around to this btw.)

**Comment by jdorfman** [comment]
@Timmmm all good. Feel free to reopen if you want. Better to just open an new PR since this is from 2018
