### ISSUE TITLE
Change Intellij LSP client owner and repository details

### ISSUE THREAD

**Issue by NipunaRanasinghe** [langserver/langserver.github.io#122]
Since the author of the [current repository](https://github.com/gtache/intellij-lsp) is not around to maintain plugin releases and get the fixes merged, we have started developments on a new fork as a new organization. Therefore requesting to update the Maintainer and repository details as follows.

**Maintainer:** [IntelliJ LSP Community](https://github.com/intellij-lsp)
**Repository:** [github.com/intellij-lsp/intellij-lsp-plugin](https://github.com/intellij-lsp/intellij-lsp-plugin)

**Comment by keegancsmith** [comment]
Hi @NipunaRanasinghe please just send a PR with the new details.
