### ISSUE TITLE
go-langserver recommends using bingo

### ISSUE THREAD

**Issue by theimpostor** [langserver/langserver.github.io#136]
sourcegraph's go-langserver has a note on its readme:

`Note: We have deprioritized work on this language server for use in editors in favor of Google's upcoming Go language server. It is in the best interests of the community to only have a single language server. If you want to use a Go language server with your editor in the meantime, try https://github.com/saibing/bingo, which is a partial fork of this repository with fixes for Go modules and other editor bugs.`

Seems like the table should at least reference bingo.

**Comment by keegancsmith** [comment]
Add a PR and we'll merge it.
