### ISSUE TITLE
Microsoft LSP Homepage

### ISSUE THREAD

**Issue by ShalokShalom** [langserver/langserver.github.io#155]
Hi there :hugs: 

Which one is the one and only? I contributed to the above one and realised two different ones could be distracting since one is always out of date. Would you sync with that one of Microsoft?

https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by dadlerj** [comment]
Hi @ShalokShalom! Yeah, sorry for any confusion — we originally created this site as an internal tool to keep track of the capabilities that each langserver provided (neither Microsoft's original GitHub wiki page nor their current version were designed to get to that level of detail). We hear that end users like to be able to see what functionality they'll get from a langserver without reading each README (or actually diving into the code and searching for `ServerCapabilities`).

This site also has some requirements that Microsoft's does not have, such as requiring that language servers be open source and platform-agnostic to be listed (so you won't find Microsoft's C++ langserver on this page).

We have no plans to merge the two sites, and haven't spoken to Microsoft about it (language server updates tend to be relatively infrequent, so hopefully it's not a big pain to update both). If there's strong community interest, though, we'd be happy to see if Microsoft was interested.

**Comment by ShalokShalom** [comment]
File watcher on their Github repo in order to see new commits, or simply watch their repo with the build in Github feature.

I added Gluon, and will do this for this repo here soon too.
Then we can check and compare, which other languages are not merged now.

I also think it's possible to merge these two pages and offer some menu point to actually select/sort which requirements should be applied. Such as being open source and agnostic about the platform, etc. I do this, and invite everyone else.

:hugs:

**Comment by ShalokShalom** [comment]
Just as an information: Kate adds currently support on the server side. The code for the implementation is actually the same one that is used in QtCreator and I am very excited about both. QtCreator can actually implement for itself, while Kate can get some help. Especially because there is currently very less awareness about this port, also because it's relatively new. Fresh implementations can often get some help, maybe create some special section on the homepage, eg some blog or news feed in order to attract people into development.
