### ISSUE TITLE
ada_langserver supports Code Completion and Workspace symbols

### ISSUE THREAD

**Issue by TamaMcGlinn** [langserver/langserver.github.io#179]
As the title says; I installed ada_language_server from Adacore (https://github.com/AdaCore/ada_language_server) and code completion works correctly, as do workspace symbols. I did not test diagnostics yet.

**Comment by jdorfman** [comment]
Going to close this out. If you want to submit a PR we will merge it.

**Comment by TamaMcGlinn** [comment]
Okay, [here you go](https://github.com/langserver/langserver.github.io/pull/292). By the way, your readme still indicates you would accept an issue just as well:

```
Please file issues or submit pull requests for any additions, suggestions, or corrections in this repository.
```
