### ISSUE TITLE
Add Kate editor to editors matrix

### ISSUE THREAD

**Issue by christoph-cullmann** [langserver/langserver.github.io#186]
Current supported features (19.12 release):

* Code completion
* Hover
* Jump to def
* Find references
* Diagnostics

Homepage:

https://kate-editor.org/

Repository (LSP client included in the main repo):

https://invent.kde.org/kde/kate

**Comment by keegancsmith** [comment]
Hi @christoph-cullmann. Could you create a PR adding kate to the editors matrix?

**Comment by christoph-cullmann** [comment]
Sure, done ;=)

**Comment by keegancsmith** [comment]
Thanks
