### ISSUE TITLE
Another C# based language server implementation

### ISSUE THREAD

**Issue by solmersa** [langserver/langserver.github.io#20]
Here is the link:
https://github.com/CXuesong/LanguageServer.NET

Also here https://github.com/CXuesong/MwLanguageServer is an implementation for the mediawiki markup.

**Comment by felixfbecker** [comment]
Would appreciate a PR :)

**Comment by solmersa** [comment]
Ok, I sent the PR.
https://github.com/langserver/langserver.github.io/pull/21
