### ISSUE TITLE
Fix JSON link

### ISSUE THREAD

**Issue by alexkreidler** [langserver/langserver.github.io#205]
The link to the VSCode JSON language server is no longer accurate. 

It points to: https://github.com/Microsoft/vscode/tree/master/extensions/json

However, the real language server is implemented here:
https://github.com/microsoft/vscode/tree/master/extensions/json-language-features/server
and in the rest of the `json-language-features` extension.

**Comment by keegancsmith** [comment]
@alexkreidler do you mind creating a PR for this?

**Comment by jdorfman** [comment]
Thanks @alexkreidler
