### ISSUE TITLE
Add JSON variants

### ISSUE THREAD

**Issue by alexkreidler** [langserver/langserver.github.io#206]
The VSCode [JSON language server](https://github.com/microsoft/vscode/tree/master/extensions/json-language-features/server) also includes support for [JSON Schema](https://json-schema.org/).

With JSON Schema and [JSON-LD](https://json-ld.org/) gaining wider adoption, it's important to note the support or lack thereof of various JSON language server implementations for these technologies.

I propose either
1. listing them as separate languages - technically pure JSON files don't have support for Hover or Code Completion, [this is only provided based on JSON Schema](https://github.com/microsoft/vscode/tree/master/extensions/json-language-features/server#server-capabilities). If another implementation were to use JSON-LD to add descriptions on hover, it would need to be separate
2. adding a note describing the level of support for them

**Comment by keegancsmith** [comment]
@alexkreidler Both options sound fine to me. Want to send a pull request?

**Comment by goyalyashpal** [comment]
no response for ~3 years, can this issue be closed?
