### ISSUE TITLE
Add GNOME Vala Language Server (GVls)

### ISSUE THREAD

**Issue by esodan** [langserver/langserver.github.io#215]
GVls is a [LSP](https://gitlab.gnome.org/esodan/gvls) implemention for a Client and Server, written in [Vala](https://valadoc.org), it used by GNOME Builder for its Vala support.

GVls supports:

- Code completion
- Hover
- Jump to def
- Workspace symbols
- Diagnostics

**Comment by keegancsmith** [comment]
Hi @esodan happy to include this. Could you send a PR adding it?
