### ISSUE TITLE
Include language servers providing Diagnostics

### ISSUE THREAD

**Issue by henryju** [langserver/langserver.github.io#22]
We developed a language server (SonarLint) that run static analysis for different languages, but no other language features. The current way to present language servers "per language" doesn't fit well with our server implementation.

**Comment by felixfbecker** [comment]
Suggestions?

**Comment by henryju** [comment]
One option is to add a column "Diagnostics" in the main table. And add one SonarLint entry for each supported languages, with only the "Diagnotics" cell checked.

I don't know if similar language server will appear (ie language servers exposing static analysis tools), but in this case maybe a dedicated section would be better.

**Comment by felixfbecker** [comment]
I am not aware of other language servers that work for multiple languages, I think LSP is mostly designed around having one language server per language or in specific cases, multiple per language (like specific linters). Our language server x feature is meant to reflect that. We could add SonarLint as a normal row with just diagnostics checked and the other cells `N/A` with white background. wdyt?

**Comment by henryju** [comment]
Yep, that would be great, and you can change later if needed. FYI SonarLint currently provide Diagnostics for JavaScript, PHP and Python (others will come later).

Thanks

**Comment by henryju** [comment]
Done: #23

**Comment by chrismwendt** [comment]
Resolved by https://github.com/langserver/langserver.github.io/pull/23
