### ISSUE TITLE
Add Deno LSP

### ISSUE THREAD

**Issue by rottencandy** [langserver/langserver.github.io#233]
Deno 1.6 comes with a built-in LSP: https://deno.land/posts/v1.6#built-in-deno-language-server

I'd be happy to create a PR for this, if there is interest in adding `deno` to the list, since it's a runtime and not a language.
If not, feel free to close the issue.

**Comment by keegancsmith** [comment]
please create a PR. Anything which speaks LSP deserves to live on this page :)
