### ISSUE TITLE
LSP Community Slack Workspace

### ISSUE THREAD

**Issue by pajatopmr** [langserver/langserver.github.io#238]
There is now a Slack workspace (Community LSP) for public discussions of LSP clients, servers, sdks, etc.
This [open invitation](https://join.slack.com/t/community-lsp/shared_invite/zt-kwb1gcgn-GSTyNqD0UToRyhUA0gz5gg) can be used to join.
It would be good to post this information.

**Comment by keegancsmith** [comment]
@pajatopmr thanks for creating the slack. I see this slack is brand new and doesn't have any members yet. A bit of a chicken and egg problem, but it seems like a good place to advertise once some community of LSP devs are using it.

**Comment by pajatopmr** [comment]
The key to devs is the open invitation. Publish that and the devs will come. I did this with the Clean Coders Slack workspace and we are now up to 300 plus devs. So, if you act now rather than wait, you will be helping the community. I will be looking for other options to get the invite out but your facility is very important in the LSP community.

**Comment by keegancsmith** [comment]
@pajatopmr Ok lets link to it :) Can you send a PR adding a link?

**Comment by pajatopmr** [comment]
That's awesome! I'll get right on it.

-pmr

**Comment by ceronman** [comment]
Hi, I have tried to join this slack, but apparently it's only available to `@pajato.com` email addresses.

**Comment by pajatopmr** [comment]
Getting signed into Slack is a mystery to me.  I think if you already have
a Slack account, you can get in. Or if your email domain is registered you
can get it. Or is you have an invitation you can get it. Here's a new
invitation:
https://join.slack.com/t/community-lsp/shared_invite/zt-lk2qf7ch-yZoa2e0pEJ5mHRbU_l6O5g

Previously I could generate a never ending link but I cannot do that any
longer. :-(

Good luck and sorry I cannot help you better.

-pmr

**Comment by WilcoKruijer** [comment]
I'm confused, why can I only join the Slack with a `@github.com` or `@gitlab.com` email address?

<img width="410" alt="image" src="https://user-images.githubusercontent.com/1809836/116399059-cad44800-a828-11eb-9a83-7c2f48b2cade.png">

**Comment by pajatopmr** [comment]
I'm guessing this is a Slack thing, probably legacy (before Slack was
acquired by Salesforce).

A minor point, but you only need to have an account on Github or Gitlab,
not an email address from either of those domains. As Slack is targeted to
a technical audience, Github and Gitlab make a lot of sense since most
developers are likely to have an account on either or both of them. Hope
that helps.

Here's an invitation (that expries in 30 days) if anyone needs one:
https://join.slack.com/t/community-lsp/shared_invite/zt-pmje2z1x-LFG60o8UspAKIcBLoLcakQ

-pmr
