### ISSUE TITLE
Language Server plugin for CodeMirror 6

### ISSUE THREAD

**Issue by hjr265** [langserver/langserver.github.io#246]
I have built an extension for the upcoming version/rewrite of [CodeMirror](https://codemirror.net/6/) to provide Language Server features:

https://www.npmjs.com/package/codemirror-languageserver

https://github.com/FurqanSoftware/codemirror-languageserver

Here is a screencap of it in action:

https://user-images.githubusercontent.com/348107/120008984-53e3c800-bffd-11eb-92df-0afd179bcd7e.mp4

Currently, it supports code completion, hover and diagnostics. 

Would it be okay if I send a pull request adding a row to the table in langserver.org?

**Comment by keegancsmith** [comment]
Sure
