### ISSUE TITLE
sourcegraph/javascript-typescript-langserver is deprecated - theia-ide/typescript-language-server is recommended

### ISSUE THREAD

**Issue by neelkarma** [langserver/langserver.github.io#248]
From the sourcegraph/javascript-typescript-langserver README:

> ⚠️ This project is no longer maintained ... On top of that, over time we simplified our architecture for running language servers in the cloud at Sourcegraph which removed the necessity for this level of tight integration and control. Theia's TypeScript language server is a thinner wrapper around tsserver, which avoids these problems to some extent.

This affects the Javascript and Typescript rows in the language server table. Should I make a PR?

Edit: Also fyi, theia-ide/typescript-language-server, despite the name, also supports Javascript as well as Typescript

**Comment by attfarhan** [comment]
@neelkarma please make a PR 😄  thanks!
