### ISSUE TITLE
Unable to join Slack workspace

### ISSUE THREAD

**Issue by dlvhdr** [langserver/langserver.github.io#265]
The slack link in the site, for joining the channel, forces me to sign in with a github.com email address.
How do I join the channel?

`community-lsp.slack.com`

![image](https://user-images.githubusercontent.com/6196971/137630682-5c2832b7-57f1-4275-8c35-b9f6bd33d4d3.png)

**Comment by keegancsmith** [comment]
@pajatopmr runs that slack and added the link to it on langserver.org. Hopefully he can help you.

**Comment by pajatopmr** [comment]
Slack claims that this link: https://join.slack.com/t/community-lsp/shared_invite/zt-xl8fn11d-sj5E7HXPK4yuh8M183HQZQ will never expire. I'm skeptical but have at it.  Mind you, the workspace is dormant but perhaps you will be able to bring some life to it. Best of luck, one and all.
