### ISSUE TITLE
Fix Community Discussion Forums (Slack) link

### ISSUE THREAD

**Issue by MichielVerloop** [langserver/langserver.github.io#270]
Near the bottom of the site, [https://community-lsp.slack.com/](https://community-lsp.slack.com/) is linked as a public space where no invitation is required. However, it is impossible to join Slack workspaces if you don't have an email address on a pre-approved email domain or an invitation to join.

From what I've found, there are a few solutions to be considered:

1. Pre-approve popular email domains such as gmail.com, although I'm unsure if large domains can be pre-approved.
2. Have a site ask for email addresses to approve.
3. Move from Slack to a comparable application like Discord.

**Comment by keegancsmith** [comment]
Does the link mentioned here help? https://github.com/langserver/langserver.github.io/issues/265#issuecomment-946346534

If so we should update the blurb.

cc @pajatopmr

**Comment by MichielVerloop** [comment]
It works. Good to know that permanent invite links are a thing after all.

**Comment by pajatopmr** [comment]
@keegancsmith if you would, feel free to update the description to include the invite rather than saying no invite is required.

**Comment by keegancsmith** [comment]
Fixed by https://github.com/langserver/langserver.github.io/commit/5c2be049e5d6e33e8cb6d565b28fb143927bebe3
