### ISSUE TITLE
Reconsider the inclusion of non-free intelephense server

### ISSUE THREAD

**Issue by ambadyanands** [langserver/langserver.github.io#283]
Hi,

First of all thanks for this community-driven project. At [langserver.org](https://langserver.org), it states that the servers and clients **must be fully open-source** in order to qualify to be included on the list. Listing [intelephense](https://intelephense.com/eula.html) server violates this condition and I kindly request to remove the same by reverting https://github.com/langserver/langserver.github.io/commit/b6f8a1ded331233a107f991b7f8efb5d6cb331cc. Thanks again.

**Comment by kskarthik** [comment]
I also back this proposal

**Comment by keegancsmith** [comment]
FYI @beyang @sqs we state the servers needs to be OSS to be included. This seems like a position we should keep, but ccing you just in case you think it makes sense to change our conditions of inclusion. For now I will accept the revert.

Also cc @juliardi since he added the listing. I'm happy to change the decision after some debate. But for now I am going ahead with the revert.

**Comment by juliardi** [comment]
Although I am an avid supporter of open source, I am a bit baffled by Langserver's policy of only listing open source product. I will abide by your decision, but I hope Langserver can be a resource of information for finding Language Server tools regardless of license.

**Comment by ambadyanands** [comment]
>  I hope Langserver can be a resource of information for finding Language Server tools regardless of license.

@juliardi Hi, given that there is already such a list at https://microsoft.github.io/language-server-protocol/implementors/servers/, wouldn't that make this project redundant? What makes langserver project important, I believe, is its policies.

**Comment by jdorfman** [comment]
@juliardi @ambadyanands hypothetical, if we (Sourcegraph) donated this project to the community where new policies and governance could be established would this help the move this project forward?
