### ISSUE TITLE
Is Pyright a Python language server?

### ISSUE THREAD

**Issue by huppyflup** [langserver/langserver.github.io#309]
Pyright is in the list of language servers but the repo says that it's a: "Static Type Checker for Python" (https://github.com/microsoft/pyright).
With its command-line tool it doesn't seem to behave like an lsp.

**Comment by keegancsmith** [comment]
I am not sure. I think its best to follow up with the pyright community. They mention the LSP but maybe our links our now outdated? https://github.com/microsoft/pyright#community

**Comment by huppyflup** [comment]
The community section from your link says “language service functionality is associated with Pylance”, but it is mentioned as lsp in the docs in 
https://microsoft.github.io/pyright/#/installation?id=language-server and 
https://microsoft.github.io/pyright/#/features?id=language-server-support.
I don’t know if one of these is a better link because the docs seems to lack how it’s used as an lsp. The only thing I found is https://github.com/microsoft/pyright/discussions/3515

(Interestingly the microsoft list of language servers lists neither pylance nor pyright https://microsoft.github.io/language-server-protocol/implementors/servers/)

**Comment by andrewcrook** [comment]
@huppyflup 
> (Interestingly the microsoft list of language servers lists neither **pylance** 

 **pylance** is a LSP that now only works with VSCode and Visual Studio I am not sure there is any point listing it really because its not open to LSP clients in general. Microsoft now refers to it as "fully integrate support”.
 
 I am not sure but I think pyright needs a wrapper to turn it into a LSP. Pyright is actually used as a part of pylance so that’s probably why, because they want you to use their products.

**Comment by huppyflup** [comment]
If it needs a wrapper should then the wrapper be listed instead?

**Comment by Pegasust** [comment]
`pyright` provides `pyright` the CLI to type-check and report, you could theoretically write extend it as a static type checker by using `pyright --json`. Another big player for static typing that is officially embraced by Python core is [mypy](https://github.com/python/mypy), which is used by [python-lsp-server](https://github.com/python-lsp/python-lsp-server) as a type-checking backend.

`pyright` does ship with the lsp: `pyright-langserver`, where common invocation for an LSP client is `pyright-langserver --stdio`, see [Neovim's lspconfig](https://github.com/neovim/nvim-lspconfig/blob/361a2878a41f23452457eec12a807ff59bc75882/lua/lspconfig/server_configurations/pyright.lua#L34)

So yes, `pyright` is a Python LSP that supports [static type checking based on couple of PEP](https://github.com/microsoft/pyright/blob/f68d9bf7b0f15a3445d8c8f97bf04a103f9bf769/docs/mypy-comparison.md#why-does-pyrights-behavior-differ-from-mypys) in pure TypeScript (so it theoretically does not require the Python interpreter, as long as you have the bundled executable) and [resort to typestubs for external library type information before optionally using Python interpreter and toolings to resolve and deduce transitive type context onto our project/package](https://github.com/microsoft/pyright/blob/f68d9bf7b0f15a3445d8c8f97bf04a103f9bf769/docs/import-resolution.md)

**Comment by huppyflup** [comment]
I can agree, that with `pyright-langserver` it's a language server.
