### ISSUE TITLE
Add ElixirLS to the list of language servers

### ISSUE THREAD

**Issue by colbydehart** [langserver/langserver.github.io#36]
https://github.com/JakeBecker/elixir-ls

A LSP for Elixir with support for 
- Debugger support!!!
- Inline reporting of build warnings and errors
- Documentation lookup on hover
- Go-to-definition
- Code completion

**Comment by felixfbecker** [comment]
Would you do a PR? Also, what's debugger support?

**Comment by chulkilee** [comment]
See #81

**Comment by axelson** [comment]
This can be closed because #81 is merged
