### ISSUE TITLE
Please include Dlang's serve-d

### ISSUE THREAD

**Issue by 9898287** [langserver/langserver.github.io#49]
serve-d is Microsoft language server protocol implementation for D
https://github.com/Pure-D/serve-d

This offers a completion daemon via DCD, formatter via Dfmt and various syntax checks via Dscanner
https://github.com/dlang-community/DCD
https://github.com/dlang-community/dfmt
https://github.com/dlang-community/D-Scanner

**Comment by attfarhan** [comment]
Great! Would you like to make a PR to add this in?

**Comment by 9898287** [comment]
PR open!
https://github.com/langserver/langserver.github.io/pull/57
