### ISSUE TITLE
More Vim LSP clients

### ISSUE THREAD

**Issue by ssokolow** [langserver/langserver.github.io#5]
I'm not in a position to test them at the moment, but here are a couple of Vim language server implementations you haven't listed:

1. [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) (For NeoVim only. According to the [README](https://github.com/autozimu/LanguageClient-neovim#quick-start) and the [demo GIFs](https://github.com/autozimu/images/tree/master/LanguageClient-neovim), it's got support for Code Completion (by integrating with [deoplete](https://github.com/Shougo/deoplete.nvim)), Hover, Jump to Definition, Rename, and symbol search.)

2. [prabirshrestha/vim-lsp](https://github.com/prabirshrestha/vim-lsp) (Experimental and undocumented but, unlike any other options I'm aware of, it supports Vim 8.x in addition to NeoVim. [From the code](https://github.com/prabirshrestha/vim-lsp/blob/master/example.vim#L494-L508), it appears to support Hover, Jump to Definition, and symbol search.)

I don't know how to evaluate whether something provides diagnostics, so I can't give an answer on that column.

**Comment by mqudsi** [comment]
+1 for @autozimu's implementation.

**Comment by jacwah** [comment]
The one currently listed as a Vim client (https://github.com/tjdevries/nvim-langserver-shim) does not actually support Vim. Vim != Neovim.

The only plugin I've found for Vim is https://github.com/prabirshrestha/vim-lsp. I haven't spent a lot of time on it, but it seems to work fine. Maybe it should be listed as the Vim plugin instead?

**Comment by natebosch** [comment]
There is also https://github.com/natebosch/vim-lsc - I opened a PR to add a row.
