### ISSUE TITLE
LLVM is working on a language server for Clang

### ISSUE THREAD

**Issue by ssokolow** [langserver/langserver.github.io#6]
Just under a week ago (on the 7th), an early prototype Language Server for Clang was committed to LLVM trunk:

> Add a prototype for clangd
> 
> clangd is a language server protocol implementation based on clang. It's
> supposed to provide editor integration while not suffering from the
> confined ABI of libclang.
> 
> This implementation is limited to the bare minimum functionality of
> doing (whole-document) formatting and rangeFormatting. The JSON parsing
> is based on LLVM's YAMLParser but yet most of the code of clangd is
> currently dealing with JSON serialization and deserialization.
> 
> This was only tested with VS Code so far, mileage with other LSP clients
> may vary.
>  -- https://reviews.llvm.org/rL294291

This sounds like what `Language servers > Works in progress` is for.

**Comment by felixfbecker** [comment]
Wanna do a PR?

**Comment by ssokolow** [comment]
Sorry for the delay. I've been very busy. I'll try to find time for it but I can't guarantee anything.

**Comment by ssokolow** [comment]
OK, I've started working on a PR but I'm having a little trouble with two things:

1. I'm unsure how you expect me to format the repository link for a project which doesn't have a repository of its own but, instead, lives within the much larger LLVM repository. (At the moment, it's tentatively [clang-tools-extra/trunk/clangd](https://reviews.llvm.org/diffusion/L/browse/clang-tools-extra/trunk/clangd/).

2. I'm unsure how to list the author. It appears to have been committed by a user named d0k with other LLVM developers starting to join in afterward, but d0k's nick isn't hyperlinked in the LLVM reviews system like the others are and I can't remember what LLVM policy is for attribution in these circumstances.

@d0k Given that your SO profile says you are the same person who claims to be an LLVM developer on Twitter, can you weigh in on this?

**Comment by d0k** [comment]
As you can see this is really just an early prototype. We do formatting and diagnostics right now but nothing else, and it will take a while until it gets usable.

clangd lives inside of the LLVM tree and is expected to be built there, so the only point you can link at is the clang-tools-extra repository. For authors I'd prefer if you put "LLVM Developers" or "LLVM Team" there, while I wrote the initial prototype this is a community project.

**Comment by ssokolow** [comment]
Judging by the "LSP clients" table, a row in the "Works in progress" section (ie. which doesn't yet implement any of the listed functionality in a usable way) should have all of its non-textual columns blank and yellow, so I'll focus on the remaining ones.

<table>
			<tr>
				<th>C / C++</th>
				<td><a href="http://llvm.org/">LLVM Team</a></td>
				<td class="repo"><a href="https://reviews.llvm.org/diffusion/L/browse/clang-tools-extra/trunk/clangd/">clang-tools-extra/trunk/clangd</a></td>
			</tr>
		</table>

@d0k Would this content be appropriate? (I'd especially like your feedback on my choice of link target for the repository column, since I'm unfamiliar with conventions for linking to projects using Phabricator.)

@felixfbecker Given the structure of the LLVM project, would this be reasonable text for the repository column?

**Comment by felixfbecker** [comment]
Isn't Phabricator a review tool, not a code host platform?
Other than that LGTM

**Comment by ssokolow** [comment]
@felixfbecker

Phabricator is a GitHub/BitBucket/GitLab-esque integrated hosting system which has code review as one of the contained functions. (And, like GitLab Community, it's open-source and can be self-hosted.)

**Comment by d0k** [comment]
Linking to phab is fine. We can change it to the docs once we have docs :)
